title: Cristina Gabriel # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data science professional with over 5 years of experience in extracting valuable insights from vast datasets, I have refined my expertise in data analysis, machine learning, and predictive modeling to drive strategic decisions and deliver impactful solutions across various industries including academic and government. 
  I am passionate about using data to uncover insights, drive strategic decision-making, and create value for businesses. I am currently seeking opportunities where I can contribute my expertise in data science, analysis, and machine learning to innovative and challenging projects. Let’s connect to discuss how I can bring value to your team.
  <br><br>
  <strong>Skills:</strong><br>
  Programming Languages: Python, SQL and R <br>
  Data Analysis Tools: Excel, Tableau <br>
  Database Management Tools: MySQL, PostgreSQL <br>
  Cloud Based Tools: AWS <br>
  Machine Learning: scikit-learn, TensorFlow, PyTorch <br>
  Mathematics: Biostatistics, Calculus 
  <br><br>
  <strong>Education/Certifications:</strong><br>
  IBM Certification in Data Science <br>
  Bachelors of Science; Neuroscience
  <br><br>
  <a href="https://www.linkedin.com/in/cristinagabriel91/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
