title: Cristina Gabriel # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data science professional with over 5 years of experience in extracting valuable insights from vast datasets, I have refined my expertise in data analysis, machine learning, and predictive modeling to drive strategic decisions and deliver impactful solutions across various industries including academic and government. 
  I am passionate about using data to uncover insights, drive strategic decision-making, and create value for businesses. I am currently seeking opportunities where I can contribute my expertise in data science, analysis, and machine learning to innovative and challenging projects. Let’s connect to discuss how I can bring value to your team.
  <br><br>
  <strong>Skills:</strong><br>
  <ul>
    <li> Programming Languages: Python, SQL and R </li> <br> 
    <li> Data Analysis Tools: Excel, Tableau </li> <br>
    <li> Database Management Tools: MySQL, PostgreSQL </li> <br>
    <li> Cloud Based Tools: AWS </li> <br>
    <li> Machine Learning: scikit-learn, TensorFlow, PyTorch </li> <br>
    <li> Mathematics: Biostatistics, Calculus </li> 
  </ul>
  <br><br>
  <strong>Education/Certifications:</strong><br>
  <ul>
    <li> IBM Certification in Data Science <br> </li>
    <li> Bachelors of Science; Neuroscience </li>
  </ul>
  <br><br>
  <a href="https://www.linkedin.com/in/cristinagabriel91/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
