title: Cristina Gabriel # your name (or website title) here
logo: "/images/biophoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data science professional with over 5 years of experience in extracting valuable insights from vast datasets. Expertise in data analysis, machine learning, and predictive modeling to drive strategic decisions and deliver impactful solutions across various sectors. 
   <br><br>
   <a href="https://kristy1620.github.io/">Portfolio</a> 
   <br>
   <a href="https://kristy1620.github.io/Certificates">Skills & Certificates</a>  
   <br>
   <a href="ttps://kristy1620.github.io/documents/Cristina_Gabriel_CV.pdf">View CV</a>  
  
   [View CV](https://kristy1620.github.io/documents/Cristina_Gabriel_CV.pdf)
   <br>
   <a href="https://www.linkedin.com/in/cristinagabriel91/">Contact Me on LinkedIn</a> 
  
theme: jekyll-theme-minimal
